const productsList = [
  {
    productId: "01_001",
    productTitle: "Adicolor Classics Joggers",
    productImage: "assets/01_001.jpg",
    productCategory: "Dress",
    productPrice: "$63.85",
    isOnSale: false,
    isBestSeller: true,
  },
  {
    productId: "01_002",
    productTitle: "Nike Sportswear Futura Luxe",
    productImage: "assets/01_002.jpg",
    productCategory: "Bag",
    productPrice: "$130.00",
    isOnSale: false,
    isBestSeller: true,
  },
  {
    productId: "01_003",
    productTitle: "Geometric print Scarf",
    productImage: "assets/01_003.jpg",
    productCategory: "scarf",
    productPrice: "$53.00",
    isOnSale: false,
    isBestSeller: true,
  },
  {
    productId: "01_004",
    productTitle: "Yellow Reserved Hoodie",
    productImage: "assets/01_004.jpg",
    productCategory: "Dress",
    productPrice: "$364.00",
    productSalePrice: "$155.00",
    isOnSale: true,
    isBestSeller: true,
  },
  {
    productId: "01_005",
    productTitle: "Basic Dress Green",
    productImage: "assets/01_005.jpg",
    productCategory: "Dress",
    productPrice: "$236.00",
    isOnSale: false,
    isBestSeller: false,
    isHot: true,
  },
  {
    productId: "01_006",
    productTitle: "Nike Air Zoom Pegasus",
    productImage: "assets/01_006.jpg",
    productCategory: "shoe",
    productPrice: "$220.00",
    productSalePrice: "$198.00",
    isOnSale: false,
    isBestSeller: true,
  },
  {
    productId: "01_007",
    productTitle: "Nike Repel Miler",
    productImage: "assets/01_007.jpg",
    productCategory: "Dress",
    productPrice: "$120.50",
    isOnSale: false,
    isBestSeller: true,
  },
  {
    productId: "01_006",
    productTitle: "Nike Sportswear Futura Luxe",
    productImage: "assets/01_008.jpg",
    productCategory: "Glasses",
    productPrice: "$160.00",
    isOnSale: false,
    isBestSeller: true,
  },
];

export default productsList;
